name: Build Afghan Online Bazaar APK

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Check project
        run: |
          cd Afghan_Online_Bazaar
          test -s pubspec.yaml

      - name: Generate Android files
        run: |
          cd Afghan_Online_Bazaar
          flutter create . --platforms=android

      - name: Install dependencies
        working-directory: Afghan_Online_Bazaar
        run: flutter pub get

      - name: Build APK
        working-directory: Afghan_Online_Bazaar
        run: flutter build apk --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Afghan-Online-Bazaar-APK
          path: Afghan_Online_Bazaar/build/app/outputs/flutter-apk/app-debug.apk
